'use client';
import {useEffect,useMemo,useState} from 'react';
import {useParams,useRouter} from 'next/navigation';
import MathText from '@/components/MathText';
import {getSupabase} from '@/lib/supabase';

type Q={id:string;question_text:string;options:string[];correct_option:number;positive_marks:number;negative_marks:number};
type State='unseen'|'answered'|'visited'|'review';
type Student={name:string;rollNo:string};
export default function Exam(){
 const {testId}=useParams<{testId:string}>();const router=useRouter();
 const [test,setTest]=useState<any>(null),[qs,setQs]=useState<Q[]>([]),[student,setStudent]=useState<Student|null>(null),[answers,setAnswers]=useState<Record<string,number>>({}),[states,setStates]=useState<Record<string,State>>({}),[idx,setIdx]=useState(0),[seconds,setSeconds]=useState(0),[busy,setBusy]=useState(false),[err,setErr]=useState('');
 const key=`gec-quiz:${testId}`;
 useEffect(()=>{(async()=>{try{const raw=localStorage.getItem('gec-student');if(!raw){router.replace('/');return}const st=JSON.parse(raw);setStudent(st);const s=getSupabase();const {data:t,error:te}=await s.from('tests').select('*').eq('id',testId).single();if(te)throw te;const {data:q,error:qe}=await s.from('questions').select('*').eq('test_id',testId).order('created_at',{ascending:true});if(qe)throw qe;if(!q?.length)throw new Error('This test has no questions.');setTest(t);setQs(q);const saved=localStorage.getItem(key);if(saved){const p=JSON.parse(saved);setAnswers(p.answers||{});setStates(p.states||{});setIdx(Math.min(Number(p.idx||0),q.length-1));} })().catch(e=>setErr(e instanceof Error?e.message:'Unable to load exam'))},[testId,key,router]);
 useEffect(()=>{if(!test||!qs.length)return;const update=()=>{const end=test.end_at?new Date(test.end_at).getTime():Date.now()+Number(test.duration_minutes)*60000;setSeconds(Math.max(0,Math.ceil((end-Date.now())/1000)));};update();const id=setInterval(update,1000);return()=>clearInterval(id)},[test,qs.length]);
 useEffect(()=>{if(!qs.length)return;localStorage.setItem(key,JSON.stringify({answers,states,idx}))},[answers,states,idx,key,qs.length]);
 useEffect(()=>{if(seconds!==0||busy||!qs.length)return;submit()},[seconds,busy,qs.length]);
 const current=qs[idx];const counts=useMemo(()=>{const c={unseen:0,answered:0,visited:0,review:0};qs.forEach(q=>c[states[q.id]||'unseen']++);return c},[qs,states]);
 function choose(opt:number){setAnswers(a=>({...a,[current.id]:opt}));setStates(s=>({...s,[current.id]:'answered'}))}
 function next(){if(idx<qs.length-1){setStates(s=>({...s,[current.id]:s[current.id]==='answered'?'answered':'visited'}));setIdx(i=>i+1)}}
 function clear(){setAnswers(a=>{const n={...a};delete n[current.id];return n});setStates(s=>({...s,[current.id]:'visited'}))}
 function review(){setStates(s=>({...s,[current.id]:'review'}));if(idx<qs.length-1)setIdx(i=>i+1)}
 async function submit(){if(busy||!qs.length||!student)return;setBusy(true);try{let score=0;qs.forEach(q=>{const a=answers[q.id];if(a===undefined)return;score+=a===q.correct_option?q.positive_marks:q.negative_marks});const payload={student_name:student.name,roll_no:student.rollNo,student_id:null,test_id:testId,user_answers:answers,total_score:score};const {data,error}=await getSupabase().from('test_submissions').insert(payload).select('id,access_token').single();if(error)throw error;localStorage.removeItem(key);router.replace(`/results/${data.id}?token=${data.access_token}`)}catch(e){setErr(e instanceof Error?e.message:'Submission failed');setBusy(false)}}
 const mm=String(Math.floor(seconds/60)).padStart(2,'0'),ss=String(seconds%60).padStart(2,'0');const beforeStart=test?.start_at&&Date.now()<new Date(test.start_at).getTime();
 if(err)return <main className="p-8"><div className="mx-auto max-w-xl rounded-xl bg-white p-6 shadow">{err}</div></main>;if(!test||!current||!student)return <main className="grid min-h-screen place-items-center">Loading exam…</main>;if(beforeStart)return <main className="grid min-h-screen place-items-center bg-slate-50 p-6"><div className="rounded-2xl bg-white p-8 text-center shadow"><h1 className="text-2xl font-black">{test.title}</h1><p className="mt-3 text-slate-500">The test has not started yet.</p><p className="mt-2 font-bold">Starts: {new Date(test.start_at).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</p><button onClick={()=>router.replace('/dashboard')} className="mt-6 rounded-lg bg-indigo-600 px-5 py-2 text-white">Back</button></div></main>;
 return <main className="exam-shell"><header className="flex h-16 items-center justify-between border-b bg-white px-4"><div><b>{test.title}</b><span className="ml-3 text-sm text-slate-500">{student.name} · {student.rollNo} · Q {idx+1}/{qs.length}</span></div><div className="rounded-lg bg-red-50 px-4 py-2 font-mono font-bold text-red-700">{mm}:{ss}</div></header><div className="grid min-h-[calc(100vh-64px)] lg:grid-cols-[1fr_330px]"><section className="flex flex-col border-r bg-white"><div className="flex-1 overflow-auto p-6"><div className="mb-5 flex items-center justify-between"><span className="rounded bg-slate-100 px-3 py-1 text-sm font-semibold">Question {idx+1}</span><span className="text-sm text-slate-500">+{current.positive_marks} / {current.negative_marks}</span></div><div className="text-lg leading-8"><MathText text={current.question_text}/></div><div className="mt-7 space-y-3">{current.options.map((o,i)=><button key={i} onClick={()=>choose(i)} className={`flex w-full items-start gap-3 rounded-xl border p-4 text-left ${answers[current.id]===i?'border-indigo-600 bg-indigo-50 ring-1 ring-indigo-600':'bg-white hover:bg-slate-50'}`}><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full border font-semibold">{String.fromCharCode(65+i)}</span><span><MathText text={o}/></span></button>)}</div></div><div className="flex flex-wrap gap-2 border-t bg-slate-50 p-4"><button onClick={clear} className="rounded-lg border bg-white px-4 py-2">Clear</button><button onClick={review} className="rounded-lg border bg-purple-50 px-4 py-2 text-purple-800">Mark for Review</button><button onClick={next} className="ml-auto rounded-lg bg-indigo-600 px-5 py-2 font-semibold text-white">Save & Next</button><button onClick={submit} disabled={busy} className="rounded-lg bg-red-600 px-5 py-2 font-semibold text-white">{busy?'Submitting…':'Submit'}</button></div></section><aside className="bg-slate-50 p-4"><div className="rounded-xl border bg-white p-4"><h2 className="font-bold">Question Palette</h2><div className="mt-3 grid grid-cols-5 gap-2">{qs.map((q,i)=>{const st=states[q.id]||'unseen';const cls=st==='answered'?'bg-green-500 text-white':st==='review'?'bg-purple-500 text-white':st==='visited'?'bg-red-500 text-white':'bg-slate-200 text-slate-700';return <button key={q.id} onClick={()=>{setIdx(i);if(st==='unseen')setStates(s=>({...s,[q.id]:'visited'}))}} className={`h-9 rounded ${cls}`}>{i+1}</button>})}</div><div className="mt-5 grid grid-cols-2 gap-2 text-xs"><span>Grey: {counts.unseen}</span><span className="text-red-600">Red: {counts.visited}</span><span className="text-green-600">Green: {counts.answered}</span><span className="text-purple-600">Purple: {counts.review}</span></div></div></aside></div></main>
}
