'use client';
import {useEffect,useState} from 'react';
import {getSupabase} from '@/lib/supabase';

const sample=`{"title":"Tech Quiz","duration_minutes":30,"start_at":"","questions":[{"question_text":"If \\(v=10\\) m/s and \\(t=2\\) s, displacement is?","options":["10 m","20 m","5 m","12 m"],"correct_option":1}]}`;
type Test={id:string;title:string;duration_minutes:number;total_marks:number;start_at:string|null;end_at:string|null;created_at:string};
function toIso(v:string){return v?new Date(v).toISOString():null}
export default function Admin(){
 const [json,setJson]=useState(sample),[tests,setTests]=useState<Test[]>([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<string|null>(null),[editDuration,setEditDuration]=useState(''),[editStart,setEditStart]=useState('');
 async function check(){const s=getSupabase();const {data:{user}}=await s.auth.getUser();if(!user){location.href='/admin/login';return}const {data:p}=await s.from('users').select('role').eq('id',user.id).single();if(p?.role!=='admin')location.href='/admin/login';}
 async function load(){const {data,error}=await getSupabase().from('tests').select('*').order('created_at',{ascending:false});if(error)setMsg(error.message);else setTests(data||[])}
 useEffect(()=>{check();load()},[]);
 async function create(){setBusy(true);setMsg('');try{const p=JSON.parse(json);if(!p.title||!p.duration_minutes||!Array.isArray(p.questions)||!p.questions.length)throw new Error('JSON must contain title, duration_minutes and questions[]');const start=toIso(p.start_at||'');const end=start?new Date(new Date(start).getTime()+Number(p.duration_minutes)*60000).toISOString():null;const s=getSupabase();const {data:test,error:te}=await s.from('tests').insert({title:String(p.title),duration_minutes:Number(p.duration_minutes),total_marks:p.questions.length*4,start_at:start,end_at:end}).select().single();if(te)throw te;const rows=p.questions.map((q:any)=>({test_id:test.id,question_text:String(q.question_text||''),options:q.options,correct_option:Number(q.correct_option),positive_marks:4,negative_marks:-1}));const {error:qe}=await s.from('questions').insert(rows);if(qe){await s.from('tests').delete().eq('id',test.id);throw qe}setMsg(`Created ${test.title} with ${rows.length} questions.`);setJson(sample);await load()}catch(e){setMsg(e instanceof Error?e.message:'Could not create test')}finally{setBusy(false)}}
 async function addQuestions(testId:string){setBusy(true);setMsg('');try{const p=JSON.parse(json);if(!Array.isArray(p.questions)||!p.questions.length)throw new Error('JSON must contain questions[]');const s=getSupabase();const rows=p.questions.map((q:any)=>({test_id:testId,question_text:String(q.question_text||''),options:q.options,correct_option:Number(q.correct_option),positive_marks:4,negative_marks:-1}));const {error}=await s.from('questions').insert(rows);if(error)throw error;const {count}=await s.from('questions').select('*',{count:'exact',head:true}).eq('test_id',testId);await s.from('tests').update({total_marks:Number(count||0)*4}).eq('id',testId);setMsg(`Added ${rows.length} questions.`);await load()}catch(e){setMsg(e instanceof Error?e.message:'Could not add questions')}finally{setBusy(false)}}
 async function saveEdit(t:Test){setBusy(true);try{const start=toIso(editStart);const end=start?new Date(new Date(start).getTime()+Number(editDuration)*60000).toISOString():null;const {error}=await getSupabase().from('tests').update({duration_minutes:Number(editDuration),start_at:start,end_at:end}).eq('id',t.id);if(error)throw error;setMsg('Test settings updated.');setEditing(null);await load()}catch(e){setMsg(e instanceof Error?e.message:'Update failed')}finally{setBusy(false)}}
 return <main className="min-h-screen bg-slate-50 p-5"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-white p-5 shadow-sm"><div><p className="text-sm font-semibold text-indigo-600">GEC BANKA · ADMIN</p><h1 className="text-3xl font-black">Tech Quiz Manager</h1><p className="text-sm text-slate-500">Create, increase questions, change timer and schedule live tests.</p></div><div className="flex gap-2"><a href="/" className="rounded-lg border bg-white px-4 py-2">Student page</a><button onClick={async()=>{await getSupabase().auth.signOut();location.href='/admin/login'}} className="rounded-lg border bg-white px-4 py-2">Sign out</button></div></header>
 <section className="mt-5 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Create new test</h2><p className="mt-1 text-sm text-slate-500">Set <b>start_at</b> to schedule a live test. Leave it empty to make the test available immediately.</p><textarea value={json} onChange={e=>setJson(e.target.value)} className="mt-4 min-h-[320px] w-full rounded-xl border bg-slate-950 p-4 font-mono text-sm text-white"/><div className="mt-3 flex flex-wrap gap-2"><button disabled={busy} onClick={create} className="rounded-lg bg-indigo-600 px-5 py-3 font-semibold text-white disabled:opacity-60">{busy?'Working…':'Create test'}</button></div>{msg&&<p className="mt-3 rounded-lg bg-slate-100 p-3 text-sm">{msg}</p>}</section>
 <section className="mt-5 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Manage existing tests</h2><div className="mt-4 space-y-4">{tests.map(t=><article key={t.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">{t.title}</h3><p className="text-sm text-slate-500">{t.duration_minutes} min · {t.total_marks} marks · {t.start_at?new Date(t.start_at).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'Starts immediately'}</p></div><button onClick={()=>{setEditing(t.id);setEditDuration(String(t.duration_minutes));setEditStart(t.start_at?new Date(t.start_at).toISOString().slice(0,16):'')}} className="rounded-lg border px-3 py-2">Change timer / start time</button></div>{editing===t.id&&<div className="mt-3 grid gap-2 md:grid-cols-3"><input type="number" min="1" value={editDuration} onChange={e=>setEditDuration(e.target.value)} className="rounded-lg border p-2" placeholder="Duration minutes"/><input type="datetime-local" value={editStart} onChange={e=>setEditStart(e.target.value)} className="rounded-lg border p-2"/><button onClick={()=>saveEdit(t)} className="rounded-lg bg-indigo-600 px-4 py-2 text-white">Save settings</button></div>}<div className="mt-3 rounded-lg bg-slate-50 p-3"><p className="text-sm font-semibold">Add more questions</p><button onClick={()=>addQuestions(t.id)} disabled={busy} className="mt-2 rounded-lg bg-green-600 px-4 py-2 text-white">Add questions from JSON above</button></div></article>)}{!tests.length&&<p className="text-slate-500">No tests yet.</p>}</div></section></div></main>
}
