'use client';
import { FormEvent,useState } from 'react';
import { getSupabase } from '@/lib/supabase';

export default function AdminLogin(){
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const s=getSupabase();const {error}=await s.auth.signInWithPassword({email,password});if(error)throw error;const {data:{user}}=await s.auth.getUser();if(!user)throw new Error('No authenticated user.');const {data:p,error:pe}=await s.from('users').select('role').eq('id',user.id).single();if(pe)throw pe;if(p?.role!=='admin'){await s.auth.signOut();throw new Error('This account is not an admin account.')}window.location.assign('/admin')}catch(e){setError(e instanceof Error?e.message:'Login failed')}finally{setBusy(false)}}
 return <main className="min-h-screen grid place-items-center p-6"><form onSubmit={submit} className="w-full max-w-md rounded-2xl border bg-white p-7 shadow-lg"><div className="mb-6 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-indigo-50 font-black text-indigo-700">GEC</div><h1 className="mt-4 text-2xl font-black">Admin Login</h1><p className="mt-1 text-sm text-slate-500">GEC Banka Tech Quiz</p></div><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Admin email" required className="w-full rounded-lg border p-3"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" required className="mt-3 w-full rounded-lg border p-3"/><button disabled={busy} className="mt-5 w-full rounded-lg bg-indigo-600 p-3 font-semibold text-white disabled:opacity-60">{busy?'Signing in…':'Sign in as Admin'}</button>{error&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<a href="/" className="mt-5 block text-center text-sm text-indigo-700 underline">Back to Tech Quiz</a></form></main>
}
