'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {getSupabase} from '@/lib/supabase';

type Test={id:string;title:string;duration_minutes:number;total_marks:number;start_at:string|null;end_at:string|null};
type Student={name:string;rollNo:string};
function status(t:Test){const now=Date.now();if(t.start_at&&now<new Date(t.start_at).getTime())return 'upcoming';if(t.end_at&&now>=new Date(t.end_at).getTime())return 'closed';return 'live'}
function formatStart(v:string|null){return v?new Date(v).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'Available now'}
export default function Dashboard(){
 const [student,setStudent]=useState<Student|null>(null);const [tests,setTests]=useState<Test[]>([]);const [error,setError]=useState('');
 useEffect(()=>{const raw=localStorage.getItem('gec-student');if(!raw){location.href='/';return}setStudent(JSON.parse(raw));(async()=>{const {data,error}=await getSupabase().from('tests').select('id,title,duration_minutes,total_marks,start_at,end_at').order('created_at',{ascending:false});if(error)setError(error.message);else setTests(data||[])})()},[]);
 if(!student)return <main className="grid min-h-screen place-items-center">Loading…</main>;
 return <main className="min-h-screen bg-slate-50 p-5"><div className="mx-auto max-w-5xl"><header className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-4"><div><p className="text-sm text-slate-500">GEC Banka · Tech Quiz</p><h1 className="text-2xl font-black">Welcome, {student.name}</h1><p className="text-sm text-slate-500">Roll No: {student.rollNo}</p></div><button onClick={()=>{localStorage.removeItem('gec-student');location.href='/'}} className="rounded-lg border bg-white px-4 py-2">Change student</button></div></header><section className="mt-6"><h2 className="text-xl font-bold">Available Tests</h2>{error&&<p className="mt-3 rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}<div className="mt-4 grid gap-4 md:grid-cols-2">{tests.map(t=>{const st=status(t);return <article key={t.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><h3 className="text-lg font-bold">{t.title}</h3><span className={`rounded-full px-3 py-1 text-xs font-bold ${st==='live'?'bg-green-100 text-green-700':st==='upcoming'?'bg-amber-100 text-amber-700':'bg-slate-100 text-slate-500'}`}>{st==='live'?'LIVE':st==='upcoming'?'UPCOMING':'CLOSED'}</span></div><p className="mt-2 text-sm text-slate-500">{t.duration_minutes} min · {t.total_marks} marks</p><p className="mt-1 text-xs text-slate-500">Starts: {formatStart(t.start_at)}</p>{st==='upcoming'&&<p className="mt-3 text-sm font-semibold text-amber-700">Test will open automatically at the scheduled time.</p>}{st==='live'?<Link href={`/exam/${t.id}`} className="mt-5 inline-block rounded-lg bg-indigo-600 px-4 py-2 font-semibold text-white">Start Live Test</Link>:st==='upcoming'?<button disabled className="mt-5 rounded-lg bg-slate-200 px-4 py-2 font-semibold text-slate-500">Waiting for start time</button>:<button disabled className="mt-5 rounded-lg bg-slate-200 px-4 py-2 font-semibold text-slate-500">Test closed</button>}</article>})}</div>{tests.length===0&&<div className="mt-4 rounded-xl border bg-white p-8 text-slate-500">No tests have been scheduled yet.</div>}</section></div></main>
}
